language: java
jdk:
  - oraclejdk7
  - openjdk6
before_install:
 - mkdir "$HOME/.python-eggs"
 - chmod 700 "$HOME/.python-eggs"
 - sudo apt-get update -qq
 - sudo apt-get install -qq mercurial libsqlite3-dev python-dev samtools bedtools
